# Generated by Django 2.0.2 on 2018-03-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
    ]
