# Generated by Django 2.0.2 on 2018-02-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_fillinquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('answer', models.TextField(default='')),
            ],
            bases=('question.question',),
        ),
    ]
