# Generated by Django 2.0.2 on 2018-02-21 17:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import question.Questions.Question


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(default='')),
                ('selection_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('resolution', models.TextField(default='')),
                ('category', models.IntegerField(default=1)),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=question.Questions.Question.__defaultList__, size=None)),
                ('visit_count', models.IntegerField(default=0)),
                ('source', models.TextField(default='')),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('accuracy', models.FloatField(default=0)),
            ],
            bases=('question.question',),
        ),
        migrations.CreateModel(
            name='OneChoiceChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Choice')),
            ],
            bases=('question.choice',),
        ),
        migrations.CreateModel(
            name='OneChoiceQuestion',
            fields=[
                ('choicequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.ChoiceQuestion')),
                ('answer', models.IntegerField(default=0)),
            ],
            bases=('question.choicequestion',),
        ),
    ]
