# Generated by Django 2.0.2 on 2018-02-24 10:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import question.Questions.FillInQuestion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_onechoicechoice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=question.Questions.FillInQuestion.__defaultList__, size=None)),
            ],
            bases=('question.question',),
        ),
    ]
