# Generated by Django 2.0.2 on 2018-02-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_subjectivequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('answer', models.BooleanField(default=True)),
                ('correct_count', models.IntegerField(default=0)),
            ],
            bases=('question.question',),
        ),
    ]
