# Generated by Django 2.0.2 on 2018-02-24 16:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import question.Questions.MultipleChoiceQuestion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_trueorfalsequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Choice')),
            ],
            bases=('question.choice',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('choicequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.ChoiceQuestion')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=question.Questions.MultipleChoiceQuestion.__defaultList__, size=None)),
                ('correct_count', models.IntegerField(default=0)),
            ],
            bases=('question.choicequestion',),
        ),
        migrations.AddField(
            model_name='multiplechoicechoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.MultipleChoiceQuestion'),
        ),
    ]
