# Generated by Django 2.0.2 on 2018-02-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20180226_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='accuracy_daily',
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='accuracy_weekly',
        ),
    ]
