# Generated by Django 2.0.2 on 2018-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20180226_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='correct_count_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='correct_count_weekly',
            field=models.IntegerField(default=0),
        ),
    ]
