# Generated by Django 2.0.2 on 2018-02-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_cron'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
