# Generated by Django 2.0.2 on 2018-02-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_cron_loaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron',
            name='loaded',
        ),
    ]
