# Generated by Django 2.0.2 on 2018-02-28 08:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import question.Questions.QuestionList


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_questionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='fill_in_question',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=question.Questions.QuestionList.__defaultDict__),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='multiple_choice_question',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=question.Questions.QuestionList.__defaultDict__),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='one_choice_question',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=question.Questions.QuestionList.__defaultDict__),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='subjective_question',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=question.Questions.QuestionList.__defaultDict__),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='true_or_false_question',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=question.Questions.QuestionList.__defaultDict__),
        ),
    ]
