# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='avatar/default.png', upload_to='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('lower_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('password_salt', models.CharField(max_length=8)),
                ('is_active', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('register_time', models.DateTimeField(verbose_name='register time')),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
