# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 16:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='question type and id'), default=user.models.__defaultList__, size=2), default=user.models.__defaultList__, size=100),
        ),
        migrations.AddField(
            model_name='user',
            name='flawbook',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='question type and id'), default=user.models.__defaultList__, size=2), default=user.models.__defaultList__, size=100),
        ),
    ]
