# Generated by Django 2.0.2 on 2018-03-12 09:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180128_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weakness',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=user.models.__defaultDict__),
        ),
    ]
